
name: Delete Branches
permissions: write-all

on:
  workflow_dispatch:
  push:
    paths: '.github/workflows/delete_branches.yml'
  schedule:
    - cron: '* */12 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@v2.0.0
      with:
        debug: true
        script: |
          var oneHourAgo = new Date((new Date()) - 1000*60*60);
          var branches = await github.repos.listBranches({
             owner: 'bbq-beets',
             repo: 'ForkPRCanary',
             per_page: 100
           });
           console.log(`Found ${branches.data.length} Branches`);
           for (i = 0; i < branches.data.length; i++) {
             var branchName = branches.data[i].name;
             if(branchName === "main") {
               continue 
             }
             var branch = await github.repos.getBranch({
              owner: 'bbq-beets',
              repo: 'ForkPRCanary',
              branch: branchName
             });

             console.log(`Branch ${branch.data.name} is created at ${branch.data.commit.commit.committer.date}`);
             var createTime = Date.parse(branch.data.commit.commit.committer.date);
             if(createTime < oneHourAgo) {
                var deleted = await github.git.deleteRef({
                  owner: 'bbq-beets',
                  repo: 'ForkPRCanary',
                  ref: `heads/${branchName}`,
                });

               console.log(deleted);
             }
           }
