# PR from fork should get read-only GITHUB_TOKEN and no secrets
# Workflow file should come from fork, GITHUB_SHA/REF points to merge sha/ref

name: PullRequest_Fork

on:
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    # check GITHUB_TOKEN has read only permission
    - run: |
        git pull
        echo ${{github.sha}} >> ${{github.sha}}.txt
        git add .
        git commit -am "${{github.sha}}"
        git push
      continue-on-error: true
      id: git
    - run: |
        fail the step
      if: steps.git.outcome != 'failure'

    # check we don't have secrets
    - run: |
        fail the step
      if: secrets.test == 'password123!@#'

